Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PointOfSale.DataService.Helpers;
using PointOfSale.DataService.IServices;
using PointOfSale.DataService.ViewModels;

namespace PointOfSale.Controllers
{
    //[Route("[controller]")]
    public class CategoriesController : Controller
    {
        private readonly ICategoryService _categoryService;
        private readonly ILookupService _lookupService;
        private ServiceResponse<object> _response;
        public CategoriesController(ICategoryService categoryService, ILookupService lookupService)
        {
            _categoryService = categoryService;
            _lookupService = lookupService;
            _response = new ServiceResponse<object>();
        }
        [HttpGet] //, Route("Index")
        public async Task<ActionResult> Index()
        {
            var response = await _categoryService.GetAll();
            return View(response.Data);
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            ViewBag.Status = "Create";
            _response = await _lookupService.CategoriesDrp("");
            ViewBag.CategoriesDrp = (SelectList)_response.Data;
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> Create(CategoryForCreateVM viewModel)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
                _response = await _categoryService.Create(viewModel);
                return Ok(_response);
            }
            catch (Exception ex)
            {
                _response.Success = false;
                _response.Message = ex.Message ?? ex.InnerException.ToString();
                return BadRequest(_response);
            }
        }
        [HttpGet]
        public async Task<ActionResult> Edit(int id)
        {
            ViewBag.Status = "Update";
            var response = await _categoryService.GetById(id);
            _response = await _lookupService.CategoriesDrp(response.Data.ParentCategoryId);
            ViewBag.CategoriesDrp = (SelectList)_response.Data;
            return View("Create", response.Data);
        }
        [HttpPut]
        public async Task<ActionResult> Update(int id, CategoryForUpdateVM viewModel)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }
                _response = await _categoryService.Update(id, viewModel);
                return Ok(_response);
            }
            catch (Exception ex)
            {
                _response.Success = false;
                _response.Message = ex.Message ?? ex.InnerException.ToString();
                return BadRequest(_response);
            }
        }
        [HttpDelete]
        public async Task<ActionResult> Delete(int id)
        {
            try
            {
                _response = await _categoryService.Delete(id);
                return Ok(_response);
            }
            catch (Exception ex)
            {
                _response.Success = false;
                _response.Message = ex.Message ?? ex.InnerException.ToString();
                return BadRequest(_response);
            }
        }
    }
}

Views/Categories/Create.cshtml
@model CategoryForDetailsVM

@{

    Layout = null;
    // We use same page for add and edit.
    string urlPostString = "/Categories/Create";
    if (ViewBag.Status == "Update")
    {
        urlPostString = "/Categories/Update";
    }
}

<div class="row">
    <div class="col-md-4">
        <form id="form" needs-validation novalidate="novalidate" name="form" enctype="multipart/form-data" method="post" asp-action="#@urlPostString">
            <input asp-for="Id" type="hidden" />

            <div class="form-group">
                <label class="control-label">Name</label>
                <input asp-for="Label" type="text" class="form-control" placeholder="Label" />
                @*<span asp-validation-for="Label" class="text-danger"></span>*@
            </div>
            <div class="form-group">
                <label asp-for="Code" class="control-label"></label>
                <input asp-for="Code" type="text" class="form-control" placeholder="Code" />
                @*<span asp-validation-for="Code" class="text-danger"></span>*@
            </div>
            <div class="form-group">
                <label class="control-label">Parent Category</label>
                <select asp-items="ViewBag.CategoriesDrp" class="form-control">
                    <option value="0">Select Category</option>
                </select>
                @*<span asp-validation-for="ParentCategoryId" class="text-danger"></span>*@
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" type="text" class="form-control" placeholder="Description"></textarea>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input type="file" class="form-control" />
            </div>
            @*<div class="form-group">
                    <label asp-for="Image" class="control-label"></label>
                    <input type="file" class="form-control" />
                </div>*@

            <div class="form-group">
                <input type="submit" value="@ViewBag.Status" class="btn btn-primary" />
            </div>
        </form>
        @*<button id="clickme">click me for testing</button>*@

    </div>
</div>
<div>
    <a href="#/Categories/Index">Back to List</a>
</div>

<script>

    $(function () {

        $("#form").validate({
            rules: {
                Label: "required",
                Code: "required",
            },
            messages: {
                Label: "Please enter category name",
                Code: "Please enter category code"
            },
            errorElement: "span",
            errorPlacement: function (error, element) {
                error.addClass("invalid-feedback");

                if (element.prop("type") === "checkbox") {
                    error.insertAfter(element.parent("label"));
                } else {
                    error.insertAfter(element);
                }
            },
            highlight: function (element, errorClass, validClass) {
                //debugger;
                $(element).parents(".form-group").children(".form-control").addClass("is-invalid").removeClass("is-valid");
            },
            unhighlight: function (element, errorClass, validClass) {
                //debugger;
                $(element).parents(".form-group").children(".form-control").addClass("is-valid").removeClass("is-invalid");
            }
        });
    });
    $("#form").on("submit", function (e) {
        if ($("#form").valid()) {
            routingApp.runRoute('post', '#@urlPostString');
            e.preventDefault();
            e.stopPropagation();
        }
    });

    // add dynamic create or update link

    if (IfLinkNotExist("POST", "#@urlPostString")) {
        routingApp.post("#@urlPostString", function (context) {

            var formData = new FormData($('#form')[0]);
             HttpPOST("@urlPostString", formData, function (response) {
                 if (response.success) {
                     ohSnap(response.message, { 'color': 'green' });
                     window.location.href = "#/Categories/Index";
                 }
                 else {
                     ohSnap(response.message, { 'color': 'red', 'duration': '10000' })
                     //ClearAll();
                     //window.location.reload();
                 }
             });

        });
    }

</script>

Views/Categories/Index.cshtml
@model IEnumerable<CategoryForListVM>

@{
    Layout = null;
}

<p>
    <a href="#/Categories/Create">Create New</a>
</p>
<table id="dataTable" class="table table-striped table-bordered table-responsive" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>
                Label
            </th>
            <th>
                Code
            </th>
            <th>
                Parent Category
            </th>
            <th>
                Description
            </th>

            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Label)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Code)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ParentCategory)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>

                <td>
                    <a href="#/Categories/Edit/@item.Id">Edit</a> |
                    <a href="javascript:void(0);" onclick="Delete(@item.Id)">Delete</a>
                    @*<a asp-controller="Categories" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                        <a asp-controller="Categories" asp-action="Details" asp-route-id="@item.Id">Details</a> |
                        <a asp-controller="Categories" asp-action="Delete" asp-route-id="@item.Id">Delete</a>*@
                </td>
            </tr>
        }
    </tbody>
</table>
<script>

    $(function () {
        $('#dataTable').DataTable();
        //$('#delete').on('click', function () {
        //    $.confirm({
        //        title: 'Alert!',
        //        content: 'Are you sure you want to delete this record!',
        //        buttons: {
        //            confirm: function () {
        //                $.alert('Confirmed!');
        //            },
        //            cancel: function () {

        //            }
        //        }
        //    });
        //});
    });

    
    function Delete(id) {
        $("#loader").removeClass("fadeOut").addClass("fadeIn");
        $.confirm({
            title: 'Alert!',
            content: 'Are you sure you want to delete this record!',
            buttons: {
                confirm: function () {
                    $.ajax({
                        url: '/Categories/Delete/' + id,
                        type: "DELETE",
                        success: function (response) {
                            $("#loader").removeClass("fadeIn").addClass("fadeOut");
                            if (response.success) {
                                ohSnap(response.message, { 'color': 'green' })
                                window.location.href = "#/Categories/Index";
                            }
                            else {
                                ohSnap(response.message, { 'color': 'red' })
                                //window.location.reload();
                            }
                        },
                        error: function (ex) {
                            $("#loader").removeClass("fadeIn").addClass("fadeOut");
                            ohSnap(ex.message, { 'color': 'red' });
                            //window.location.reload();
                        }
                    });
                },
                cancel: function () {

                }
            }
        });

    }

</script>